### ISSUE TITLE
Develop Versioning / Release Strategy for Crossplane-Runtime

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane-runtime#11]
### What problem are you facing?

As more repositories begin to take a dependency on `crossplane-runtime`, it is likely that different stacks will want to take a dependency on different versions of `crossplane-runtime`. Currently, this is done by pegging to a specific commit.

### How could Crossplane help solve your problem?

A more robust semantic versioning strategy should be used to allow for clearly defined changes in the library. Useful references for library versioning include:
- [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime)
- [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder)
- [controller-tools](https://github.com/kubernetes-sigs/controller-tools/releases)

**Comment by negz** [comment]
I think controller-runtime's strategy seems reasonable. My straw-man proposal to get this started would be to adopt a modified version of controller-runtime that:

* Uses Github labels instead of emojis to categorise PRs
* Disregards the Kubernetes workflow parts, since we don't use their build tooling

**Comment by negz** [comment]
> Uses Github labels instead of emojis to categorise PRs

I just started working on updating the controller-runtime docs for our needs, and realised that folks without at least "triage" access (which lets you close PRs and issues) cannot add labels to pull requests. 👎
