### ISSUE TITLE
Rename reclaimPolicy in managed resource to retentionPolicy

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane-runtime#179]
### What problem are you facing?

I have encountered this again while writing the 0.11 docs about managed resources.

`reclaimPolicy` on `PersistentVolume`s refer to what happens to the `PersistentVolume` when the claim(old claims or contemporary requirements in our case) is deleted. A different name for the current `reclaimPolicy` would make more sense since it decides on what happens to the actual cloud resource.

### How could Crossplane help solve your problem?

`retentionPolicy` or `deletionPolicy` would make more sense. Honestly, I'd be OK if we removed the field altogether and assumed managed resource is tightly coupled with external resource.

**Comment by negz** [comment]
The field exists in two places today:

* Between requirement and composite. Determines whether the composite is deleted or retained when the requirement is deleted. Has no effect on whether external resources are deleted or kept.
* Between managed resource an external resource. Determines whether the external resource is kept when the managed resource is deleted.

I don't think we should keep the name `reclaimPolicy` for either, because the semantics and behavior have diverged from the upstream (PV) field of that name.

> Honestly, I'd be OK if we removed the field altogether and assumed managed resource is tightly coupled with external resource.

Do we need to support removing an external resource from Crossplane management? i.e. Crossplane has a bug, or the consumer just doesn't like it and wants to back out without losing their infrastructure. I'm okay with considering the lifecycle coupled as long as we have some story for this; perhaps just remove the Crossplane/provider deployments, remove the finalizer, then delete the CR?

**Comment by muvaf** [comment]
> Between requirement and composite. Determines whether the composite is deleted or retained when the requirement is deleted. Has no effect on whether external resources are deleted or kept.

I think that matches the current behavior between PV and PVC. I'm not sure about whether we need to keep the a name that has `claim` in it. But the behavior is same so I'd be OK if we kept it for users to know what it is immediately.

> Do we need to support removing an external resource from Crossplane management? i.e. Crossplane has a bug, or the consumer just doesn't like it and wants to back out without losing their infrastructure.

I think we do, the use case you're describing makes sense to me. I remember a case where a user reached out saying cloudsql controller was sending requests to GCP API aggresively, we were able to provide a mitigation by fixing a field but that was just a nice coincidence. I can see the case where we promise a fix with a patch release and user doesn't want the controller to reconcile the resource until their setup is patched.

> I'm okay with considering the lifecycle coupled as long as we have some story for this; perhaps just remove the Crossplane/provider deployments, remove the finalizer, then delete the CR?

This is the current possible way but it's cumbersome for users to do this, in fact, maybe impossible if they don't have access to deployment of crossplane. Maybe we can allow an annotation to be added by the user like `crossplane.io/disable-reconciliation: true` and controller would not do any operation on that CR. Then they'd delete and remove the finalizer, which won't cause any API calls to provider.

**Comment by negz** [comment]
> I think that matches the current behavior between PV and PVC.

@muvaf I would argue it doesn't; it matches a subset of the behaviour between PV and PVC. A PV reclaim policy also dictates what happens to the actual underlying volume when the PVC is deleted. If we exactly matched the PVC behaviour (which I'm not saying we should) setting `reclaimPolicy: Retain` on a composite resource would ensure the composed resources were retained when the composite was deleted.

**Comment by negz** [comment]
I spent some time thinking about this today. I suggest:

* We rename the managed resource level `reclaimPolicy` - I like `deletionPolicy`.
* We remove the composite resource level `reclaimPolicy`.

In practice this would mean:

* Deleting a requirement would always delete its underlying composite resource.
* Deleting a composite resource would alway delete all of its underlying managed resources (this is the case today).
* Deleting a managed resource may or may not delete the external resource depending on its `deletionPolicy`.

**Comment by hasheddan** [comment]
+1 to above

**Comment by negz** [comment]
A few more thoughts on this, in no particular order:

The managed resource level feels like the right granularity for this setting to me. I could imagine authoring a composite resource that was a mix of stateful and stateless resources (e.g. a Kubernetes control plane with a few node pools, or a database with a few firewall rules) and wanting to retain only the stateful external resources when the composite was deleted.

If we assume managed resources will always be part of a composite resource, this means the `Composition` author decides what will happen to external resources when their composite is deleted. We suspect one case for retaining external resources will be to remove them from Crossplane management; for example because the platform operator wants to temporarily remove some resources from Crossplane management to avoid a bug, or because they want to stop using Crossplane altogether. In this case the platform operator could edit the appropriate `Composition` before deleting the composite resource to ensure this would be the case. I'm assuming platform operators will always be able to at least edit a `Composition`, even if it was created by a distinct platform builder persona.

Strongly coupling the lifecycle of the requirement to the composite resource (after binding, in static provisioning case) seems reasonable to me. Updates are already strongly coupled, and I've never personally been a proponent of allowing composite resources (or managed resources) to easily be reused across multiple requirements (or claims).

**Comment by muvaf** [comment]
I agree that it makes sense to have this on managed resource and manage what happens to external resource when managed resource is deleted. Specifically, disabling Crossplane or moving the management of a cloud resource from one Crossplane cluster to another one should not be too hard. Thinking of persistent volumes, this use case doesn't really exist because volume is fundamentally coupled with the app that's run in *that* cluster but that's not the case for us; for example VPC or a big database cluster isn't really coupled with one cluster or one app.

In case of reclaim policy between requirement<>composite resource, I believe the reason Kubernetes has that notion is about making sure you don't lose data accidentally and maybe keeping it for backup/copy to another cluster(because pv<>volume is strongly coupled) rather than re-use of the same volume by a different claim. In that regard, these use cases are either captured by managed<>external policy or not relevant for non-volume resources. So, we don't need to keep that policy for the reasons Kubernetes keeps it.

There is a use case for the agent that we should be able to migrate a Crossplane cluster to another one but since this will be a "hand-held" operation, our CLI or set of commands that do this operation can make sure nothing is accidentally deleted.

**Comment by negz** [comment]
> There is a use case for the agent that we should be able to migrate a Crossplane cluster to another one but since this will be a "hand-held" operation, our CLI or set of commands that do this operation can make sure nothing is accidentally deleted.

Yeah, I think along these lines there's often the option to "perform surgery", i.e.:

1. Stop Crossplane so that it won't re-add finalizers to edited resources.
2. Edit the requirement and composite to remove the finalizer and binding references.
3. Restart Crossplane.

This isn't feasible for folks on hosted platforms (e.g. Upbound Cloud) though, since they don't have the option to stop Crossplane.
