### ISSUE TITLE
Late initialize deletion policy

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane-runtime#205]
### What problem are you facing?

When `spec.deletionPolicy` is left empty, managed reconciler makes a [defaulting decision](https://github.com/crossplane/crossplane-runtime/blob/fa795a5/pkg/reconciler/managed/reconciler.go#L551) and assumes it's `Delete`. While the decision is not surprising, when a user gets the resource, it's not immediate to them that the policy is `Delete`.

### How could Crossplane help solve your problem?

We can have an `Initializer`, the mechanism we use for defaulting, that will assign `Delete` policy to `spec.deletionPolicy` if it's empty so that it's more apparent to the user. Additionally, we can possibly remove the defaulting logic from managed reconciler but I feel that we'd want to keep it to handle edge cases.

**Comment by negz** [comment]
iirc v1 CRDs support defaulting in their schema - we might consider bumping to v1 CRDs in our next release so that we can remove some of the simpler defaulting initializers. Not sure if controller-runtime supports this yet though.

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting

**Comment by negz** [comment]
We should be able to default this now, similar to what we did in https://github.com/crossplane/crossplane-runtime/pull/252
