### ISSUE TITLE
Allow setting SecretType in writeConntectionSecretToRef

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane-runtime#226]
### What problem are you facing?

Currently, all managed resources with connection information write secrets of type `connection.crosspane.io/v1alpha1`.

https://github.com/crossplane/crossplane-runtime/blob/378a57303ea0a2d13ae21668044364ad8d1035d9/pkg/resource/resource.go#L37

### How could Crossplane help solve your problem?

Allowing a user to set alternate secret types (with a default of `connection.crosspane.io/v1alpha1`) could enable the case where controllers for external secret stores (such as Vault or SecretManager), could watch for secrets of a given type in the cluster and sync them to the external store.

**Comment by negz** [comment]
@hasheddan Is the idea that we would want to make this configurable because controllers for secret stores like Vault expect a fixed secret type? i.e. They won't accept ours? One downside of making this configurable is that we won't easily be able to classify secrets as a Crossplane connection secret or not. I wonder if we could address this by supporting different secret types, but logically not considering them a 'connection secret'. e.g. As part of rethinking `writeConnectionSecretToRef` perhaps we support something like `writeCustomSecretToRef`? 🤔

**Comment by chlunde** [comment]
For a [tekton ssh key](https://github.com/tektoncd/pipeline/blob/main/docs/auth.md#configuring-ssh-auth-authentication-for-git), we would have to set the type *and* annotatations:

```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: <private-key>
```

**Comment by chlunde** [comment]
@turkenh this is fixed by https://github.com/crossplane/crossplane/pull/3029 ? Both annotations and type?

**Comment by turkenh** [comment]
@chlunde correct, example https://marketplace.upbound.io/providers/upbound/provider-aws/v0.15.0/resources/rds.aws.upbound.io/Instance/v1beta1#doc:spec-publishConnectionDetailsTo-metadata
