### ISSUE TITLE
Keep info between CRUD methods?

### ISSUE THREAD

**Issue by RealFatCat** [crossplane/crossplane-runtime#309]
### What problem are you facing?

Hi,
We are trying to write controller for a resource, that never deletes an external resource. External provider keeps this resource as a some sort of a "record" about an event.
So when someone runs `kubectl delete` on that resource, we should delete this resource from kubernetes just like the `deletionPolicy` is set to `Orphan`.

On the creation of the resource, external provider returns the ID of this new resource.
We save this ID as external name with `meta.SetExternalName()`, right in the Create() method.
On `Delete()` we tried to unset external name, but this code resets it:
https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reconciler/managed/api.go#L180
Because of this reset, `Observe()` will always show that resource exists => deletion hangs forever.

Our workaround is in `Observe()` method.  Besides the ID, we check existance of deletetionTimestamp annotation via `meta.WasDeleted()`.

### How could Crossplane help solve your problem?

May be we loose something and there is a better way to keep and change info (our ID as example), that we got inside CRUD methods?
Or may be there is a way to mark resource as already deleted?

**Comment by muvaf** [comment]
@RealFatCat The reconciler expects the external name to never be unset. I think checking for `meta.WasDeleted` in `Observe` is OK but another way to achieve what you'd like to do could be to have an [initializer](https://github.com/crossplane/crossplane-runtime/blob/86fb15d/pkg/reconciler/managed/reconciler.go#L563) that always sets the `deletionPolicy` to `Orphan` so that you make sure that at no point in the lifecycle of the managed resource the policy can be set to `Delete`.

Feel free to reopen if this wouldn't work for you.
