### ISSUE TITLE
Requeue with exponential backoff

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane-runtime#40]
### What problem are you facing?

Both the resource claim and managed resource reconcilers requeue a reconcile after exactly 30 seconds when they encounter an error (unless the error is known to be unrecoverable). Ideally we'd retry a little sooner with a reasonably capped exponential backoff.

Note that controller-runtime applies exponential backoff when a reconciler returns `{Requeue: true}`, and/or an error. Unfortunately the backoff starts at 5ms and doubles until it reaches a little over 16 minutes, and this is not configurable. This leads to situations like https://github.com/crossplaneio/crossplane/issues/241, in which a resource could take much longer to reconcile than expected, for reasons that are not obvious to users.

### How could Crossplane help solve your problem?

The various reconcilers we ship in crossplane-runtime could support exponential backoff. I believe it's important that this backoff be:

* Bounded appropriately for the controller in question..
* Discoverable by users who do not have access to Crossplane and/or Stack pod logs

We could implement this ourselves by manipulating `RequeueAfter`, but ideally we'd avoid reinventing controller-runtime's wheels. I've raised https://github.com/kubernetes-sigs/controller-runtime/issues/631 requesting controller-runtime allow us to plug in our own backoff logic.

**Comment by negz** [comment]
Note that configurable exponential backoff (https://github.com/kubernetes-sigs/controller-runtime/pull/731) made it into https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.5.1.

**Comment by hasheddan** [comment]
`controller-runtime` takes a pretty simple approach based on what you return in `reconcile.Result`. You can view the source [here](https://github.com/kubernetes-sigs/controller-runtime/blob/16bf3ad036b908d897543c415fcc0bafc5cec711/pkg/internal/controller/controller.go#L297), but it essentially boils down to (in order):
1. If you return an error it will add the request to the queue with the passed rate limiting interface.
2. If you return `RequeueAfter: <vaule>`, the request is added to the queue with the specified delay.
3. If you return `Requeue: true`, the request is added to the queue with the passed rate limiting interface.

The rate limiting interface is passed at controller setup time as part of the [builder `WithOptions`](https://github.com/kubernetes-sigs/controller-runtime/blob/16bf3ad036b908d897543c415fcc0bafc5cec711/pkg/builder/controller.go#L148). The [default rate limiter](https://github.com/kubernetes-sigs/controller-runtime/blob/16bf3ad036b908d897543c415fcc0bafc5cec711/pkg/controller/controller.go#L117) is a ["max of" limiter](https://github.com/kubernetes/client-go/blob/20732a1bc198ab57de644af498fa75e73fa44c08/util/workqueue/default_rate_limiters.go#L40) that uses both a bucket and per-item rate limiting approach. The per-item rate limiter uses a base delay of 5 milliseconds and a max delay of 1000 seconds (this is already described in the issue body, see here for what that [backoff schedule looks like](http://backoffcalculator.com/?rate=2&attempts=18&interval=0.005)). 

We return `RequeueAfter: <value>` [pretty](https://github.com/crossplane/crossplane-runtime/blob/45bc6d50351e8e12b1da7ca21281d754eb76fb09/pkg/reconciler/managed/reconciler.go#L585) | [much](https://github.com/crossplane/crossplane-runtime/blob/45bc6d50351e8e12b1da7ca21281d754eb76fb09/pkg/reconciler/managed/reconciler.go#L598) | [everywhere](https://github.com/crossplane/crossplane-runtime/blob/45bc6d50351e8e12b1da7ca21281d754eb76fb09/pkg/reconciler/managed/reconciler.go#L615) in the managed reconciler unless we have an error occur while actually talking to the API server (e.g. updating the status of a resource). This means that for any error that involves interacting with the external API (e.g. AWS), we are resigned to wait a hard-coded period (typically 30 seconds) before trying again, even if the error is expected to resolve quickly or is expected to take a long time to resolve (e.g. a resource we are erroneously detecting an update required for and issuing failed update requests for every 30 seconds). This means we frequently either wait longer than needed, or not long enough.

There are two primary options for improving this scenario:
1. We use this exponential backoff implementation (or potentially our own that we plug in, or something like the [fast then slow rate limiter](https://github.com/kubernetes/client-go/blob/20732a1bc198ab57de644af498fa75e73fa44c08/util/workqueue/default_rate_limiters.go#L125) in `client-go`) and return an error in both the case where we error talking to the API server _and_ we error with an operation against the external API. This would be a simple option that wouldn't necessarily require any consumers of crossplane-runtime to change code, but it would also mean that talking to the API server and talking to external APIs would be tightly coupled as a failure domain.
2. We could impose a separate backoff implementation in the managed reconciler for errors with the external API that we currently handle with `RequeueAfter: <value>`. This would allow us to still use a retry that makes sense with the API server (i.e. if we fail with a request to the API server we expect that it will succeed within the next couple of tries, meaning that a delay of 5 milliseconds and a quick escalation makes sense), and a separate one with external APIs. A good example of this would be the aforementioned case where we constantly issue updates to the external API for a resource. In that case we would probably want something similar to a variation of the fast then slow rate limiter where we might try every 5 seconds for a time, then every 30 seconds, then move to something much larger (i.e. resign to the fact that we aren't going to fix it) such as multiple hours.

I am in favor of option (2) primarily due to the fact that we may want to also rate limit _successful_ operations of the managed reconciler. This would primarily be applicable in a scenario where we have a controller continuously detect that an update is needed, requests an update, and gets a successful response. Using our own rate limiting / backoff implementation on top of the one provided by controller-runtime would mean that we could handle a case where many sequential updates were made successfully and backoff in that "non-error" situation as well.

Lastly, consumers of the managed reconciler could always override the backoff we implement with one that makes sense to the behavior of the specific managed resource, so they would not be locked in to whatever we decide is the most appropriate general case solution.

/cc @negz @muvaf @kasey

**Comment by negz** [comment]
I prefer to keep it simple for the time being and go with option one. I'd like to avoid building our own backoff layer until we know that we need to. I suspect that using a relatively well tuned controller-runtime rate limiter will go a long way even if it only handles failed operations, and even if it treats all failed operations equally (i.e. doesn't distinguish between external API failures, API server failures, etc).

I'm not familiar with the fast then slow rate limiter, but I'm wary of ever backing off to more than a couple of minutes unless we have some way to make it really obvious to users that we're reconciling very infrequently. My hunch would be to backoff from retrying about once a second to retrying about once a minute (indefinitely), especially if we were rate limiting at the controller-manager scope rather than the controller scope. i.e. It would be nice to be able to guarantee we'd only hit the AWS API at most once a second even if we were reconciling hundreds of AWS managed resources.

Somewhat tangentially, we might want to make our happy path speculative requeue frequency configurable. I believe many reconcilers have a `WithLongWait` option, but they're not plumbed up to anything. It's hard to choose a setting that works for everyone here, so I think ideally we'd let folks decide how frequently we should poll external APIs. I imagine the happy-path polling interval would correspond pretty well with the cap for exponential backoff when we're experiencing an error. i.e. If it's okay to poll every 60 seconds in the happy path it's probably fine to poll every 60 seconds while we wait for an error to resolve.

**Comment by negz** [comment]
@hasheddan This is pretty much done now from a controller-runtime perspective, right? Should we close this?

**Comment by hasheddan** [comment]
@negz yep sounds good :+1:
